name: CI

on:
  push:
    branches:
      - master
  pull_request:
    braches:
      - master

jobs:
  build:
      name: 'Build and Push'
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [10, 20, 22]

      steps:
        - name: Checkout source code
          uses: actions/checkout@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'yarn'
            
        - name: Install dependencies
          run: yarn

        - name: Running Tests
          run: yarn test