name: CI

on:
  push:
    branches:
      - master
  pull_request:
    braches:
      - master

jobs:
  build:
      name: 'Build and Push 1'
      runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
