name: CI

on:
  push:
    branches:
      - master
  pull_request:
    braches:
      - master

jobs:
  build:
      name: 'Build and Push'
      runs-on: ubuntu-latest

      steps:
        - name: Checkout source code
          uses: actions/checkout@v4
          with:
            node-version: '22'
